apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- if .Values.storage.keep }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end}}
  labels:
    {{- include "FileRise.labels" . | nindent 4 }}
  name: filerise-uploads
spec:
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.storage.uploads.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filerise-users
spec:
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.storage.users.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filerise-metadata
spec:
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.storage.metadata.size }}