name: Helm Linting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-helm-chart:
    permissions:
      contents: read
      packages: write
      security-events: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'config'
          hide-progress: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'