name: Helm Package and Publish

on:
  workflow_run:
    workflows: ["Update Chart.yaml and README"]
    types:
      - completed

jobs:
  package-helm-chart:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@ba754150c9dbbaa912ae0ac3cfba43f84195cef2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package
        run: |
          mkdir -p packaged
          for chart in ./*; do
            if [ -d "$chart" ] && [ -f "$chart/Chart.yaml" ]; then
                helm package $chart -d packaged
            fi
          done
      - name: Push
        run: |
          cd packaged
          for chart in ./*; do
            helm push $chart oci://ghcr.io/${{ github.repository }}
          done
