name: Trivy Single Chart Scan

on:
  workflow_dispatch:
    inputs:
      chart:
        required: true
        type: string

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'config'
          hide-progress: true
          format: 'sarif'
          output: 'trivy-results-${{ github.event.inputs.chart }}.sarif'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          scan-ref: ${{ github.event.inputs.chart }}
